{% set version="0.0.2" %}
{% set md5="df7cc9b66db627de782cc5da2381c852" %}
package:
  name: drippipline
  version: {{ version }}

build:
  number: 0
  string: kuan
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

source:
  url: https://github.com/PEHGP/DripPipline/archive/refs/tags/v{{ version }}.tar.gz
  md5: {{ md5 }}

requirements:
  host:
    - python >=3.7
    - r-base >=4.1.0
    - numpy >=1.18.1
  run:
    - python >=3.7
    - pandas >=1.0.1
    - biopython >=1.78
    - numpy >=1.18.1
    - scipy >=1.4.1
    - matplotlib-base >=3.1.3
    - seaborn >=0.10.0
    - bowtie2 >=2.3.5.1
    - picard >=2.24.2
    - homer >=4.11
    - bedtools >=2.29.2
    - samtools >=1.7
    - macs2 >=2.2.7.1
    - deeptools >=3.5.0
    - r-gplots >=3.1.1
    - bioconductor-mfuzz >=2.52.0
    - bioconductor-deseq2 >=1.32.0
    - ucsc-bedgraphtobigwig


test:
  imports:
    - piplines
  commands:
    - ssDRIPSeqAnalysis.py

about:
  home: https://github.com/PEHGP/DripPipline
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: "Useful tools for the analysis of ssDRIP-seq data"
  doc_url: https://github.com/PEHGP/DripPipline/wiki
  dev_url: https://github.com/PEHGP/DripPipline
